[options]
; Chemins d’addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Connexion PostgreSQL
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

; Mot de passe maître
admin_passwd = admin

; Log level
log_level = info

; Interfaces
http_interface  = 0.0.0.0
xmlrpc_interface = 0.0.0.0
