{
    'name': 'PCS Documents',
    'version': '18.0.1.0.0',
    'license': 'LGPL-3',
    'category': 'Manufacturing',
    'summary': 'PCS — production documents, piece barcodes, department transactions and stock cards',
    'depends': [
        'web',
        'sis_document',
        'pdp_product',
        'pdp_stone',
        'pdp_labor',
        'pdp_metal',
        'pdp_picture',
        'ps_utilities',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/pcs_divisions.xml',
        'data/pcs_departments.xml',
        'data/pcs_settings.xml',
        'data/pcs_ssp_wire.xml',
        'views/department_views.xml',
        'report/report_action.xml',
        'report/report_stock_card.xml',
        'report/report_priority_list.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
