services:
  db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    env_file: .env
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      # (optionnel) laisse plutôt le host/user/pass dans odoo.conf pour éviter la double source d'info
    volumes:
      - odoo_data:/var/lib/odoo/.local/share/Odoo   # << filestore + sessions
      - ./rubicon_addons:/mnt/extra-addons
      - ./data/pictures:/mnt/extra-addons/pictures:ro
      - ./external_addons:/mnt/external-addons
      - ./odoo_conf/odoo.conf:/etc/odoo/odoo.conf:ro

volumes:
  db-data:
  odoo_data:
