services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # Vos modules perso
      - ./rubicon_addons:/mnt/extra-addons
      # Monte tout le dossier de config sur /etc/odoo
      - ./odoo_conf:/etc/odoo:ro
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo

volumes:
  db-data:
