services:

  db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    env_file: .env
    depends_on:
      - db
    ports:
      - "8069:8069"
    # volumes:
    #   # Vos modules perso
    #   - ./rubicon_addons:/mnt/extra-addons
    #   # Monte tout le dossier de config sur /etc/odoo
    #   - ./odoo_conf:/etc/odoo:ro
    # environment:
    #   HOST: ${DB_HOST}
    #   USER: ${DB_USER}
    #   PASSWORD: ${DB_PASS}

volumes:
  db-data:
