@startuml
skinparam classAttributeIconSize 0
hide circle
hide methods
class "pdp.addon.cost" as pdp_addon_cost {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - addon_id : m2o→pdp.addon.type
  - create_uid : m2o→res.users
  - currency_id : m2o→res.currency
  - product_id : m2o→pdp.product
  - write_uid : m2o→res.users
  - cost : monetary
}
class "pdp.addon.type" as pdp_addon_type {
  + id : integer
  - code : char
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
}
class "pdp.api.jwt" as pdp_api_jwt {
  + id : integer
}
class "pdp.api.service" as pdp_api_service {
  + id : integer
}
class "pdp.frontend.service" as pdp_frontend_service {
  + id : integer
}
class "pdp.labor.cost.model" as pdp_labor_cost_model {
  + id : integer
  - display_name : char
  - metal : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - currency_id : m2o→res.currency
  - labor_id : m2o→pdp.labor.type
  - model_id : m2o→pdp.product.model
  - write_uid : m2o→res.users
  - cost : monetary
}
class "pdp.labor.cost.product" as pdp_labor_cost_product {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - currency_id : m2o→res.currency
  - labor_id : m2o→pdp.labor.type
  - product_id : m2o→pdp.product
  - write_uid : m2o→res.users
  - cost : monetary
}
class "pdp.labor.type" as pdp_labor_type {
  + id : integer
  - code : char
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
}
class "pdp.margin" as pdp_margin {
  + id : integer
  - code : char
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
}
class "pdp.margin.addon" as pdp_margin_addon {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - rate : float
  - id : integer
  - addon_id : m2o→pdp.addon.type
  - create_uid : m2o→res.users
  - margin_id : m2o→pdp.margin
  - write_uid : m2o→res.users
}
class "pdp.margin.labor" as pdp_margin_labor {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - rate : float
  - id : integer
  - create_uid : m2o→res.users
  - labor_id : m2o→pdp.labor.type
  - margin_id : m2o→pdp.margin
  - write_uid : m2o→res.users
}
class "pdp.margin.metal" as pdp_margin_metal {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - rate : float
  - id : integer
  - create_uid : m2o→res.users
  - margin_id : m2o→pdp.margin
  - metal_purity_id : m2o→pdp.metal.purity
  - write_uid : m2o→res.users
}
class "pdp.margin.part" as pdp_margin_part {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - rate : float
  - id : integer
  - create_uid : m2o→res.users
  - margin_id : m2o→pdp.margin
  - write_uid : m2o→res.users
}
class "pdp.margin.stone" as pdp_margin_stone {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - rate : float
  - id : integer
  - create_uid : m2o→res.users
  - margin_id : m2o→pdp.margin
  - stone_type_id : m2o→pdp.stone.type
  - write_uid : m2o→res.users
}
class "pdp.margin.stone.conditional" as pdp_margin_stone_conditional {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - rate : float
  - id : integer
  - create_uid : m2o→res.users
  - currency_id : m2o→res.currency
  - margin_id : m2o→pdp.margin
  - stone_cat_id : m2o→pdp.stone.category
  - write_uid : m2o→res.users
  - comparative_cost : monetary
  - operator : selection
}
class "pdp.market.metal" as pdp_market_metal {
  + id : integer
  - code : char
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - base_currency_id : m2o→res.currency
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
  - base_unit : selection
}
class "pdp.market.price" as pdp_market_price {
  + id : integer
  - display_name : char
  - date : date
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - currency_id : m2o→res.currency
  - metal_id : m2o→pdp.market.metal
  - source_id : m2o→pdp.market.source
  - write_uid : m2o→res.users
  - price : monetary
}
class "pdp.market.provider.nymex" as pdp_market_provider_nymex {
  + id : integer
}
class "pdp.market.source" as pdp_market_source {
  + id : integer
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
  - type : selection
  - config_json : text
}
class "pdp.metal" as pdp_metal {
  + id : integer
  - gold : boolean
  - plating : boolean
  - reference : boolean
  - code : char
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - currency_id : m2o→res.currency
  - market_metal_id : m2o→pdp.market.metal
  - write_uid : m2o→res.users
  - cost : monetary
  - cost_method : selection
}
class "pdp.metal.alloy" as pdp_metal_alloy {
  + id : integer
  - display_name : char
  - name : char
  - variant_code : char
  - create_date : datetime
  - write_date : datetime
  - yield_factor : float
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
  - line_ids : o2m→pdp.metal.alloy.line
}
class "pdp.metal.alloy.line" as pdp_metal_alloy_line {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - ratio : float
  - id : integer
  - alloy_id : m2o→pdp.metal.alloy
  - create_uid : m2o→res.users
  - metal_id : m2o→pdp.market.metal
  - write_uid : m2o→res.users
}
class "pdp.metal.parameter" as pdp_metal_parameter {
  + id : integer
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - loss_percentage : float
  - risk_factor : float
  - id : integer
  - create_uid : m2o→res.users
  - metal_id : m2o→pdp.metal
  - write_uid : m2o→res.users
  - composition : text
}
class "pdp.metal.price.service" as pdp_metal_price_service {
  + id : integer
}
class "pdp.metal.purity" as pdp_metal_purity {
  + id : integer
  - code : char
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - percent : float
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
}
class "pdp.part" as pdp_part {
  + id : integer
  - code : char
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
  - cost_ids : o2m→pdp.part.cost
}
class "pdp.part.cost" as pdp_part_cost {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - currency_id : m2o→res.currency
  - part_id : m2o→pdp.part
  - purity_id : m2o→pdp.metal.purity
  - write_uid : m2o→res.users
  - cost : monetary
}
class "pdp.picture" as pdp_picture {
  + id : integer
  - image : binary
  - image_1920 : binary
  - active : boolean
  - checksum : char
  - display_name : char
  - filename : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - model_id : m2o→pdp.product.model
  - write_uid : m2o→res.users
}
class "pdp.price.product" as pdp_price_product {
  + id : integer
  - display_name : char
  - date : date
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - detail_json : json
  - create_uid : m2o→res.users
  - currency_id : m2o→res.currency
  - margin_id : m2o→pdp.margin
  - product_id : m2o→pdp.product
  - write_uid : m2o→res.users
  - cost : monetary
  - margin : monetary
  - price : monetary
}
class "pdp.price.service" as pdp_price_service {
  + id : integer
}
class "pdp.product" as pdp_product {
  + id : integer
  - model_picture_image : binary
  - active : boolean
  - in_collection : boolean
  - code : char
  - display_name : char
  - metal : char
  - frontend_date : date
  - create_date : datetime
  - write_date : datetime
  - frontend_usd_rate : float
  - frontend_variant_count : integer
  - id : integer
  - frontend_variant_ids : m2m→pdp.product
  - category_id : m2o→pdp.product.category
  - create_uid : m2o→res.users
  - frontend_currency_id : m2o→res.currency
  - frontend_margin_id : m2o→pdp.margin
  - frontend_purity_id : m2o→pdp.metal.purity
  - model_id : m2o→pdp.product.model
  - stone_composition_id : m2o→pdp.product.stone.composition
  - write_uid : m2o→res.users
  - frontend_labor_cost : monetary
  - frontend_labor_margin : monetary
  - frontend_labor_price : monetary
  - frontend_metal_cost : monetary
  - frontend_metal_margin : monetary
  - frontend_metal_price : monetary
  - frontend_misc_cost : monetary
  - frontend_misc_margin : monetary
  - frontend_misc_price : monetary
  - frontend_parts_cost : monetary
  - frontend_parts_margin : monetary
  - frontend_parts_price : monetary
  - frontend_stone_cost : monetary
  - frontend_stone_margin : monetary
  - frontend_stone_price : monetary
  - frontend_total_cost : monetary
  - frontend_total_margin : monetary
  - frontend_total_price : monetary
  - part_ids : o2m→pdp.product.part
  ...
}
class "pdp.product.category" as pdp_product_category {
  + id : integer
  - code : char
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - waste : float
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
  - model_ids : o2m→pdp.product.model
}
class "pdp.product.model" as pdp_product_model {
  + id : integer
  - picture_image : binary
  - code : char
  - display_name : char
  - drawing : char
  - quotation : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - matching_model_ids : m2m→pdp.product.model
  - sibling_model_ids : m2m→pdp.product.model
  - category_id : m2o→pdp.product.category
  - create_uid : m2o→res.users
  - parent_model_id : m2o→pdp.product.model
  - write_uid : m2o→res.users
  - metal_weights_ids : o2m→pdp.product.model.metal
}
class "pdp.product.model.matching" as pdp_product_model_matching {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - model_one_id : m2o→pdp.product.model
  - model_two_id : m2o→pdp.product.model
  - write_uid : m2o→res.users
}
class "pdp.product.model.metal" as pdp_product_model_metal {
  + id : integer
  - display_name : char
  - metal_version : char
  - create_date : datetime
  - write_date : datetime
  - weight : float
  - id : integer
  - create_uid : m2o→res.users
  - metal_id : m2o→pdp.metal
  - model_id : m2o→pdp.product.model
  - purity_id : m2o→pdp.metal.purity
  - write_uid : m2o→res.users
}
class "pdp.product.part" as pdp_product_part {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - quantity : integer
  - create_uid : m2o→res.users
  - part_id : m2o→pdp.part
  - product_id : m2o→pdp.product
  - write_uid : m2o→res.users
}
class "pdp.product.stone" as pdp_product_stone {
  + id : integer
  - display_name : char
  - reshaped_weight : char
  - weight : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - pieces : integer
  - composition_id : m2o→pdp.product.stone.composition
  - create_uid : m2o→res.users
  - reshaped_shape_id : m2o→pdp.stone.shape
  - reshaped_size_id : m2o→pdp.stone.size
  - stone_id : m2o→pdp.stone
  - write_uid : m2o→res.users
}
class "pdp.product.stone.composition" as pdp_product_stone_composition {
  + id : integer
  - code : char
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
  - stone_line_ids : o2m→pdp.product.stone
}
class "pdp.stone" as pdp_stone {
  + id : integer
  - code : char
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - currency_id : m2o→res.currency
  - shade_id : m2o→pdp.stone.shade
  - shape_id : m2o→pdp.stone.shape
  - size_id : m2o→pdp.stone.size
  - type_id : m2o→pdp.stone.type
  - write_uid : m2o→res.users
  - cost : monetary
}
class "pdp.stone.category" as pdp_stone_category {
  + id : integer
  - active : boolean
  - code : char
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
  - type_ids : o2m→pdp.stone.type
}
class "pdp.stone.shade" as pdp_stone_shade {
  + id : integer
  - code : char
  - display_name : char
  - shade : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
}
class "pdp.stone.shape" as pdp_stone_shape {
  + id : integer
  - code : char
  - display_name : char
  - shape : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
}
class "pdp.stone.size" as pdp_stone_size {
  + id : integer
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - id : integer
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
}
class "pdp.stone.type" as pdp_stone_type {
  + id : integer
  - active : boolean
  - code : char
  - display_name : char
  - name : char
  - create_date : datetime
  - write_date : datetime
  - density : float
  - id : integer
  - category_id : m2o→pdp.stone.category
  - create_uid : m2o→res.users
  - write_uid : m2o→res.users
}
class "pdp.stone.weight" as pdp_stone_weight {
  + id : integer
  - display_name : char
  - create_date : datetime
  - write_date : datetime
  - weight : float
  - id : integer
  - create_uid : m2o→res.users
  - shade_id : m2o→pdp.stone.shade
  - shape_id : m2o→pdp.stone.shape
  - size_id : m2o→pdp.stone.size
  - type_id : m2o→pdp.stone.type
  - write_uid : m2o→res.users
}
pdp_addon_cost --> pdp_addon_type : addon_id
pdp_addon_cost --> pdp_product : product_id
pdp_labor_cost_model --> pdp_labor_type : labor_id
pdp_labor_cost_model --> pdp_product_model : model_id
pdp_labor_cost_product --> pdp_labor_type : labor_id
pdp_labor_cost_product --> pdp_product : product_id
pdp_margin_addon --> pdp_addon_type : addon_id
pdp_margin_addon --> pdp_margin : margin_id
pdp_margin_labor --> pdp_labor_type : labor_id
pdp_margin_labor --> pdp_margin : margin_id
pdp_margin_metal --> pdp_margin : margin_id
pdp_margin_metal --> pdp_metal_purity : metal_purity_id
pdp_margin_part --> pdp_margin : margin_id
pdp_margin_stone --> pdp_margin : margin_id
pdp_margin_stone --> pdp_stone_type : stone_type_id
pdp_margin_stone_conditional --> pdp_margin : margin_id
pdp_margin_stone_conditional --> pdp_stone_category : stone_cat_id
pdp_market_price --> pdp_market_metal : metal_id
pdp_market_price --> pdp_market_source : source_id
pdp_metal --> pdp_market_metal : market_metal_id
pdp_metal_alloy ..> pdp_metal_alloy_line : line_ids (o2m)
pdp_metal_alloy_line --> pdp_market_metal : metal_id
pdp_metal_alloy_line --> pdp_metal_alloy : alloy_id
pdp_metal_parameter --> pdp_metal : metal_id
pdp_part ..> pdp_part_cost : cost_ids (o2m)
pdp_part_cost --> pdp_metal_purity : purity_id
pdp_part_cost --> pdp_part : part_id
pdp_picture --> pdp_product_model : model_id
pdp_price_product --> pdp_margin : margin_id
pdp_price_product --> pdp_product : product_id
pdp_product --> pdp_margin : frontend_margin_id
pdp_product --> pdp_metal_purity : frontend_purity_id
pdp_product -- pdp_product : frontend_variant_ids
pdp_product --> pdp_product_category : category_id
pdp_product --> pdp_product_model : model_id
pdp_product ..> pdp_product_part : part_ids (o2m)
pdp_product --> pdp_product_stone_composition : stone_composition_id
pdp_product_category ..> pdp_product_model : model_ids (o2m)
pdp_product_model --> pdp_product_category : category_id
pdp_product_model -- pdp_product_model : matching_model_ids
pdp_product_model -- pdp_product_model : sibling_model_ids
pdp_product_model --> pdp_product_model : parent_model_id
pdp_product_model ..> pdp_product_model_metal : metal_weights_ids (o2m)
pdp_product_model_matching --> pdp_product_model : model_one_id
pdp_product_model_matching --> pdp_product_model : model_two_id
pdp_product_model_metal --> pdp_metal : metal_id
pdp_product_model_metal --> pdp_metal_purity : purity_id
pdp_product_model_metal --> pdp_product_model : model_id
pdp_product_part --> pdp_part : part_id
pdp_product_part --> pdp_product : product_id
pdp_product_stone --> pdp_product_stone_composition : composition_id
pdp_product_stone --> pdp_stone : stone_id
pdp_product_stone --> pdp_stone_shape : reshaped_shape_id
pdp_product_stone --> pdp_stone_size : reshaped_size_id
pdp_product_stone_composition ..> pdp_product_stone : stone_line_ids (o2m)
pdp_stone --> pdp_stone_shade : shade_id
pdp_stone --> pdp_stone_shape : shape_id
pdp_stone --> pdp_stone_size : size_id
pdp_stone --> pdp_stone_type : type_id
pdp_stone_category ..> pdp_stone_type : type_ids (o2m)
pdp_stone_type --> pdp_stone_category : category_id
pdp_stone_weight --> pdp_stone_shade : shade_id
pdp_stone_weight --> pdp_stone_shape : shape_id
pdp_stone_weight --> pdp_stone_size : size_id
pdp_stone_weight --> pdp_stone_type : type_id
@enduml