"""Initial models

Revision ID: 727dee78cdf6
Revises: 
Create Date: 2025-06-19 10:28:04.212350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727dee78cdf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('gold_purities',
    sa.Column('name', sa.String(length=3), nullable=False),
    sa.Column('percent', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('margin_miscs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('margins',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.CHAR(length=5), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_gold', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stone_categories',
    sa.Column('id', sa.CHAR(length=1), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stone_shades',
    sa.Column('shade', sa.CHAR(length=5), nullable=False),
    sa.Column('description', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('shade')
    )
    op.create_table('stone_shapes',
    sa.Column('shape', sa.CHAR(length=5), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('shape')
    )
    op.create_table('stone_sizes',
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('size')
    )
    op.create_table('metals',
    sa.Column('id', sa.CHAR(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ucost', sa.Numeric(precision=18), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('apply_plating', sa.Boolean(), nullable=True),
    sa.Column('is_gold', sa.Boolean(), nullable=True),
    sa.Column('purity', sa.String(length=3), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['purity'], ['gold_purities.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.CHAR(length=5), nullable=False),
    sa.Column('purity_name', sa.CHAR(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['purity_name'], ['gold_purities.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'purity_name', name='uq_part_costs_purity')
    )
    op.create_table('stone_types',
    sa.Column('category_id', sa.CHAR(length=1), nullable=False),
    sa.Column('id', sa.CHAR(length=5), nullable=False),
    sa.Column('type_name', sa.String(length=20), nullable=False),
    sa.Column('density', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['stone_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stones',
    sa.Column('type_id', sa.CHAR(length=5), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shape', sa.CHAR(length=5), nullable=False),
    sa.Column('shade', sa.CHAR(length=5), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('item_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['shade'], ['stone_shades.shade'], ),
    sa.ForeignKeyConstraint(['shape'], ['stone_shapes.shape'], ),
    sa.ForeignKeyConstraint(['size'], ['stone_sizes.size'], ),
    sa.ForeignKeyConstraint(['type_id'], ['stone_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stone_lot_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stone_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stone_id'], ['stones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stone_lot_cost')
    op.drop_table('stones')
    op.drop_table('stone_types')
    op.drop_table('part_costs')
    op.drop_table('metals')
    op.drop_table('stone_sizes')
    op.drop_table('stone_shapes')
    op.drop_table('stone_shades')
    op.drop_table('stone_categories')
    op.drop_table('parts')
    op.drop_table('margins')
    op.drop_table('margin_miscs')
    op.drop_table('items')
    op.drop_table('gold_purities')
    op.drop_table('currencies')
    # ### end Alembic commands ###
