{
    "name": "PDP API Service",
    "version": "1.0.0",
    "summary": "REST API Layer for PDP with JWT Authentication",
    "category": "Technical",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "pdp_product",
        "pdp_price",
        "pdp_metal",
        "pdp_stone",
        "pdp_labor",
        "pdp_margin",
    ],
    "data": [],
    "installable": True,
    "application": False,
}
