#!/bin/bash
# Harden the security configuration of the demo server.
# Usage: ./ops/harden_demo.sh [--restart]
#   --restart : restart odoo_demo after the update
#
# This script:
#   1. Generates a strong admin_passwd and applies it to odoo_demo.conf
#   2. Enables list_db=False, proxy_mode=True, workers, limits
#   3. Verifies that .env.demo contains a secure DEMO_ADMIN_PASSWORD

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONF_FILE="$SCRIPT_DIR/odoo_conf/odoo_demo.conf"
ENV_FILE="$SCRIPT_DIR/.env.demo"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.demo.yml"
RESTART="${1:-}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ── Pre-flight checks ──────────────────────────────────────────────────────
if [ ! -f "$CONF_FILE" ]; then
  echo -e "${RED}Error: $CONF_FILE not found.${NC}"
  echo "Create this file from odoo_conf/odoo_demo.conf.example before continuing."
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo -e "${RED}Error: $ENV_FILE not found.${NC}"
  echo "Create this file from .env.demo.example before continuing."
  exit 1
fi

source "$ENV_FILE"

if [ -z "$DEMO_ADMIN_PASSWORD" ] || [ "$DEMO_ADMIN_PASSWORD" = "CHANGE_ME" ]; then
  echo -e "${RED}SECURITY ERROR: DEMO_ADMIN_PASSWORD not set or is CHANGE_ME in .env.demo${NC}"
  echo "Set a strong password before continuing."
  exit 1
fi

echo -e "${GREEN}=== Hardening demo configuration ===${NC}"
echo ""

# ── Generate strong admin_passwd ───────────────────────────────────────────
ADMIN_PASSWD=$(python3 -c "import secrets; print(secrets.token_hex(24))")
echo -e "${YELLOW}admin_passwd generated (48 hex chars).${NC}"
echo "This password protects /web/database/manager."

# ── Apply settings to odoo_demo.conf ──────────────────────────────────────
# Function: add or replace an option in the .conf file
set_conf() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}\s*=" "$CONF_FILE" 2>/dev/null; then
    sed -i "s|^${key}\s*=.*|${key} = ${value}|" "$CONF_FILE"
  else
    echo "${key} = ${value}" >> "$CONF_FILE"
  fi
}

echo ""
echo "Applying security settings..."

set_conf "admin_passwd"       "$ADMIN_PASSWD"
set_conf "list_db"            "False"
set_conf "proxy_mode"         "True"
set_conf "workers"            "2"
set_conf "max_cron_threads"   "1"
set_conf "limit_time_cpu"     "60"
set_conf "limit_time_real"    "120"
set_conf "limit_memory_hard"  "2684354560"

echo ""
echo -e "${GREEN}Settings applied to $CONF_FILE:${NC}"
echo "  admin_passwd       = [48 chars, not shown]"
echo "  list_db            = False"
echo "  proxy_mode         = True"
echo "  workers            = 2"
echo "  max_cron_threads   = 1"
echo "  limit_time_cpu     = 60"
echo "  limit_time_real    = 120"
echo "  limit_memory_hard  = 2684354560 (2.5 GB)"

# ── Save admin_passwd to a local secure file ───────────────────────────────
SECRETS_FILE="$SCRIPT_DIR/.demo_secrets"
echo "# Generated by harden_demo.sh — DO NOT COMMIT" > "$SECRETS_FILE"
echo "DEMO_DB_MANAGER_PASSWORD=$ADMIN_PASSWD" >> "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"
echo ""
echo -e "${YELLOW}admin_passwd saved to .demo_secrets (chmod 600, gitignored).${NC}"

# ── Ensure .demo_secrets is gitignored ────────────────────────────────────
GITIGNORE="$SCRIPT_DIR/.gitignore"
if ! grep -q "\.demo_secrets" "$GITIGNORE" 2>/dev/null; then
  echo ".demo_secrets" >> "$GITIGNORE"
fi

# ── Restart if requested ───────────────────────────────────────────────────
if [ "$RESTART" = "--restart" ]; then
  echo ""
  echo "Restarting odoo_demo..."
  docker compose -f "$COMPOSE_FILE" restart odoo_demo
  echo -e "${GREEN}odoo_demo restarted.${NC}"
fi

echo ""
echo -e "${GREEN}=== Hardening complete ===${NC}"
echo ""
echo "Next steps:"
echo "  1. Verify the Cloudflare tunnel is active"
echo "  2. Configure firewall: ./ops/setup_firewall.sh"
echo "  3. Test: curl http://localhost:8070/web/health"
if [ "$RESTART" != "--restart" ]; then
  echo "  4. Restart odoo_demo:"
  echo "     docker compose -f docker-compose.demo.yml restart odoo_demo"
fi
